name: Deploy to Workshop

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: wiremod/gmod-upload@master
        with:
          id: 3412004213
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_USERNAME: ${{ secrets.WORKSHOP_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.WORKSHOP_PASSWORD }}
